[project]
name = "backend"
version = "0.1.0"
description = "DriveRip backend component code"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "daphne>=4.2.3",
    "django>=6.1.1",
    "django-cors-headers>=4.9.0",
    "django-filter>=26.1",
    "djangorestframework>=3.18.1",
    "djangorestframework-simplejwt>=5.5.1",
    "google-ai-generativelanguage>=0.6.15",
    "google-api-core>=2.25.2",
    "google-api-python-client>=2.200.0",
    "google-auth>=2.58.0",
    "google-auth-httplib2>=0.4.2",
    "google-genai>=2.22.0",
    "google-generativeai>=0.8.6",
    "googleapis-common-protos>=1.75.0",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.3",
    "whitenoise[brotli]>=6.12.0",
]
