# Generated by Django 6.1.1 on 2026-09-10 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mechanic", "0001_initial"),
        ("parts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("BUYER_SELLER", "Buyer-Seller"),
                            ("CUSTOMER_MECHANIC", "Customer-Mechanic"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=20,
                        verbose_name="conversation type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last message at"
                    ),
                ),
                (
                    "participant1_last_read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="participant1 last read at"
                    ),
                ),
                (
                    "participant2_last_read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="participant2 last read at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "participant1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_participant1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_participant2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_hire_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="mechanic.mechanichirerequest",
                    ),
                ),
                (
                    "related_spare_part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="parts.sparepart",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat conversation",
                "verbose_name_plural": "chat conversations",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text Message"),
                            ("IMAGE", "Image Message"),
                            ("FILE", "File Message"),
                            ("SYSTEM", "System Message"),
                        ],
                        default="TEXT",
                        max_length=10,
                        verbose_name="message type",
                    ),
                ),
                ("content", models.TextField(verbose_name="message content")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="chat_images/",
                        verbose_name="image",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="chat_files/",
                        verbose_name="file",
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="edited"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="deleted"),
                ),
                (
                    "read_by_participant1",
                    models.BooleanField(
                        default=False, verbose_name="read by participant1"
                    ),
                ),
                (
                    "read_by_participant2",
                    models.BooleanField(
                        default=False, verbose_name="read by participant2"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatconversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "chat message",
                "verbose_name_plural": "chat messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=[
                    "participant1",
                    "participant2",
                    "related_spare_part",
                    "related_hire_request",
                ],
                name="ucrp",
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["last_message_at"], name="conversation_last_message_at"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatconversation",
            unique_together={
                (
                    "participant1",
                    "participant2",
                    "related_spare_part",
                    "related_hire_request",
                )
            },
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "created_at"], name="chat_message_conversation"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "created_at"], name="chat_message_sender"
            ),
        ),
    ]
