# Generated by Django 6.1.1 on 2026-09-10 17:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="shop name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="province"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="district"
                    ),
                ),
                ("address", models.TextField(verbose_name="address")),
                ("phone", models.CharField(max_length=15, verbose_name="phone")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "business_license",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="business license"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=50, verbose_name="tax ID"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop_logos/",
                        verbose_name="shop logo",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="average rating",
                    ),
                ),
                (
                    "total_ratings",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total ratings"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "shop",
                "verbose_name_plural": "shops",
                "indexes": [
                    models.Index(
                        fields=["seller", "name"], name="unique_shop_per_seller"
                    )
                ],
                "unique_together": {("seller", "name")},
            },
        ),
    ]
