# Generated by Django 6.1.1 on 2026-09-10 17:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mechanic", "0001_initial"),
        ("parts", "0001_initial"),
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating_type",
                    models.CharField(
                        choices=[
                            ("USER", "User Rating"),
                            ("SHOP", "Shop Rating"),
                            ("SPARE_PART", "Spare Part Rating"),
                            ("MECHANIC", "Mechanic Rating"),
                            ("MECHANIC_SERVICE", "Mechanic Service Rating"),
                        ],
                        max_length=20,
                        verbose_name="rating type",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rating",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "rated_hire_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="mechanic.mechanichirerequest",
                    ),
                ),
                (
                    "rated_mechanic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="mechanic.mechanicprofile",
                    ),
                ),
                (
                    "rated_shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="shop.shop",
                    ),
                ),
                (
                    "rated_spare_part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="parts.sparepart",
                    ),
                ),
                (
                    "rated_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "rating",
                "verbose_name_plural": "ratings",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("USER", "User Review"),
                            ("SHOP", "Shop Review"),
                            ("SPARE_PART", "Spare Part Review"),
                            ("MECHANIC", "Mechanic Review"),
                            ("MECHANIC_SERVICE", "Mechanic Service Review"),
                        ],
                        max_length=20,
                        verbose_name="review type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("content", models.TextField(verbose_name="review content")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="rating.rating",
                    ),
                ),
                (
                    "reviewed_hire_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="mechanic.mechanichirerequest",
                    ),
                ),
                (
                    "reviewed_mechanic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="mechanic.mechanicprofile",
                    ),
                ),
                (
                    "reviewed_shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.shop",
                    ),
                ),
                (
                    "reviewed_spare_part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="parts.sparepart",
                    ),
                ),
                (
                    "reviewed_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["rater", "rated_user"], name="unique_user_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["rater", "rated_shop"], name="unique_shop_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["rater", "rated_spare_part"], name="unique_spare_part_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["rater", "rated_mechanic"], name="unique_mechanic_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["rater", "rated_hire_request"],
                name="unique_hire_request_rating",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={
                ("rater", "rated_hire_request"),
                ("rater", "rated_mechanic"),
                ("rater", "rated_shop"),
                ("rater", "rated_spare_part"),
                ("rater", "rated_user"),
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["reviewer", "reviewed_user"], name="unique_user_review"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["reviewer", "reviewed_shop"], name="unique_shop_review"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["reviewer", "reviewed_spare_part"],
                name="unique_spare_part_review",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["reviewer", "reviewed_mechanic"], name="unique_mechanic_review"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["reviewer", "reviewed_hire_request"],
                name="unique_hire_request_review",
            ),
        ),
    ]
