# Generated by Django 6.1.1 on 2026-09-11 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nic',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='NIC must be in valid format', regex='^[0-9]{10}$')], verbose_name='NIC'),
        ),
    ]
