# Generated by Django 5.2.4 on 2025-07-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vehiclecategory_user_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='shop',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='province'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='location_address',
            field=models.TextField(blank=True, verbose_name='location address'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='province'),
        ),
    ]
