# Generated by Django 5.2.4 on 2025-07-11 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shop_district_shop_province_sparepart_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('seller', 'name')},
        ),
    ]
