# Generated by Django 4.2.7 on 2025-07-17 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_order_notes_remove_order_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=10, verbose_name='status')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='last message at')),
                ('buyer_last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='buyer last read at')),
                ('seller_last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='seller last read at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to=settings.AUTH_USER_MODEL)),
                ('related_spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='main.sparepart')),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'SELLER'}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat conversation',
                'verbose_name_plural': 'chat conversations',
                'ordering': ['-last_message_at', '-created_at'],
                'unique_together': {('buyer', 'seller', 'related_spare_part')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text Message'), ('IMAGE', 'Image Message'), ('FILE', 'File Message'), ('SYSTEM', 'System Message')], default='TEXT', max_length=10, verbose_name='message type')),
                ('content', models.TextField(verbose_name='message content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='image')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='file')),
                ('is_edited', models.BooleanField(default=False, verbose_name='edited')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('read_by_buyer', models.BooleanField(default=False, verbose_name='read by buyer')),
                ('read_by_seller', models.BooleanField(default=False, verbose_name='read by seller')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.chatconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat message',
                'verbose_name_plural': 'chat messages',
                'ordering': ['created_at'],
            },
        ),
    ]
