# Generated by Django 4.2.7 on 2025-07-17 17:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='license number')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='years of experience')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='province')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='district')),
                ('service_area', models.TextField(blank=True, verbose_name='service area description')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='mobile mechanic')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='hourly rate')),
                ('business_name', models.CharField(blank=True, max_length=255, verbose_name='business name')),
                ('business_address', models.TextField(blank=True, verbose_name='business address')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_available', models.BooleanField(default=True, verbose_name='available for hire')),
                ('service_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='service rating')),
                ('total_service_ratings', models.PositiveIntegerField(default=0, verbose_name='total service ratings')),
                ('total_jobs_completed', models.PositiveIntegerField(default=0, verbose_name='total jobs completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('specializations', models.ManyToManyField(blank=True, related_name='specialist_mechanics', to='main.vehiclecategory')),
            ],
            options={
                'verbose_name': 'mechanic profile',
                'verbose_name_plural': 'mechanic profiles',
            },
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='read_by_buyer',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='read_by_seller',
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='conversation_type',
            field=models.CharField(choices=[('BUYER_SELLER', 'Buyer-Seller'), ('CUSTOMER_MECHANIC', 'Customer-Mechanic'), ('GENERAL', 'General')], default='GENERAL', max_length=20, verbose_name='conversation type'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='participant1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_participant1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='participant1_last_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='participant1 last read at'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='participant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_participant2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='participant2_last_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='participant2 last read at'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_by_participant1',
            field=models.BooleanField(default=False, verbose_name='read by participant1'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_by_participant2',
            field=models.BooleanField(default=False, verbose_name='read by participant2'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_type',
            field=models.CharField(choices=[('USER', 'User Rating'), ('SHOP', 'Shop Rating'), ('SPARE_PART', 'Spare Part Rating'), ('MECHANIC', 'Mechanic Rating'), ('MECHANIC_SERVICE', 'Mechanic Service Rating')], max_length=20, verbose_name='rating type'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('USER', 'User Review'), ('SHOP', 'Shop Review'), ('SPARE_PART', 'Spare Part Review'), ('MECHANIC', 'Mechanic Review'), ('MECHANIC_SERVICE', 'Mechanic Service Review')], max_length=20, verbose_name='review type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('MECHANIC', 'Mechanic')], default='BUYER', max_length=10, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='MechanicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ENGINE_REPAIR', 'Engine Repair'), ('BRAKE_SERVICE', 'Brake Service'), ('TRANSMISSION', 'Transmission Repair'), ('ELECTRICAL', 'Electrical Systems'), ('AC_SERVICE', 'AC Service'), ('BODY_WORK', 'Body Work & Painting'), ('TIRE_SERVICE', 'Tire Service'), ('OIL_CHANGE', 'Oil Change'), ('INSPECTION', 'Vehicle Inspection'), ('TOWING', 'Towing Service'), ('EMERGENCY', 'Emergency Repair'), ('OTHER', 'Other Service')], max_length=20, verbose_name='service type')),
                ('name', models.CharField(max_length=255, verbose_name='service name')),
                ('description', models.TextField(verbose_name='service description')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='base price')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price per hour')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='estimated duration (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('compatible_vehicles', models.ManyToManyField(blank=True, related_name='available_services', to='main.vehiclecategory')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.mechanicprofile')),
            ],
            options={
                'verbose_name': 'mechanic service',
                'verbose_name_plural': 'mechanic services',
            },
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'MECHANIC'}, on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MechanicHireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('ON_SITE', 'On-Site (Customer Location)'), ('SHOP', 'At Mechanic Shop'), ('ROADSIDE', 'Roadside Assistance')], default='SHOP', max_length=15, verbose_name='job type')),
                ('problem_description', models.TextField(verbose_name='problem description')),
                ('vehicle_info', models.TextField(verbose_name='vehicle information')),
                ('service_location', models.TextField(blank=True, verbose_name='service location')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='preferred date')),
                ('preferred_time', models.TimeField(blank=True, null=True, verbose_name='preferred time')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='scheduled date')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='scheduled time')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='estimated cost')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='final cost')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15, verbose_name='status')),
                ('mechanic_notes', models.TextField(blank=True, verbose_name='mechanic notes')),
                ('customer_notes', models.TextField(blank=True, verbose_name='customer notes')),
                ('work_completed', models.TextField(blank=True, verbose_name='work completed')),
                ('parts_used', models.TextField(blank=True, verbose_name='parts used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to='main.mechanicprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to='main.mechanicservice')),
            ],
            options={
                'verbose_name': 'mechanic hire request',
                'verbose_name_plural': 'mechanic hire requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatconversation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rater', 'rated_user'), ('rater', 'rated_spare_part'), ('rater', 'rated_shop')},
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='related_hire_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='main.mechanichirerequest'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_hire_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.mechanichirerequest'),
        ),
        migrations.AddField(
            model_name='rating',
            name='rated_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.mechanicprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_hire_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.mechanichirerequest'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.mechanicprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='chatconversation',
            unique_together={('participant1', 'participant2', 'related_spare_part', 'related_hire_request')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rater', 'rated_user'), ('rater', 'rated_hire_request'), ('rater', 'rated_mechanic'), ('rater', 'rated_spare_part'), ('rater', 'rated_shop')},
        ),
        migrations.CreateModel(
            name='MechanicAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, verbose_name='day of week')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='main.mechanicprofile')),
            ],
            options={
                'verbose_name': 'mechanic availability',
                'verbose_name_plural': 'mechanic availability',
                'unique_together': {('mechanic', 'day_of_week')},
            },
        ),
        migrations.RemoveField(
            model_name='chatconversation',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='chatconversation',
            name='buyer_last_read_at',
        ),
        migrations.RemoveField(
            model_name='chatconversation',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='chatconversation',
            name='seller_last_read_at',
        ),
    ]
