# Generated by Django 4.2.7 on 2025-07-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mechanicprofile_remove_chatmessage_read_by_buyer_and_more'),
    ]

    operations = [
    ]
