# Generated by Django 4.2.7 on 2025-07-17 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20250717_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='certifications',
            field=models.TextField(blank=True, verbose_name='certifications and qualifications'),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='professional description'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='participant1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_participant1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='participant2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_participant2', to=settings.AUTH_USER_MODEL),
        ),
    ]
