# Generated by Django 4.2.7 on 2025-07-18 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_mechanicprofile_certifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car3DModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='make')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('base_model_file', models.URLField(max_length=500, verbose_name='base 3D model file')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='car_3d_thumbnails/', verbose_name='thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('vehicle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_3d_models', to='main.vehiclemodel')),
            ],
            options={
                'verbose_name': '3D car model',
                'verbose_name_plural': '3D car models',
                'unique_together': {('make', 'model', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Part3DCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='part_3d_category_icons/', verbose_name='category icon')),
            ],
            options={
                'verbose_name': '3D part category',
                'verbose_name_plural': '3D part categories',
            },
        ),
        migrations.CreateModel(
            name='Part3DModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='part name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('part_model_file', models.URLField(max_length=500, verbose_name='3D model file')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='part_3d_thumbnails/', verbose_name='thumbnail')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='part_3d_previews/', verbose_name='preview image')),
                ('attachment_points', models.JSONField(blank=True, default=dict, verbose_name='attachment points')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category_3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_3d', to='main.part3dcategory')),
                ('compatible_cars_3d', models.ManyToManyField(related_name='compatible_parts_3d', to='main.car3dmodel')),
                ('spare_part', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_3d_model', to='main.sparepart')),
            ],
            options={
                'verbose_name': '3D part model',
                'verbose_name_plural': '3D part models',
            },
        ),
        migrations.CreateModel(
            name='UserCarCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='configuration name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=False, verbose_name='public configuration')),
                ('color_scheme', models.JSONField(blank=True, default=dict, verbose_name='color scheme')),
                ('material_settings', models.JSONField(blank=True, default=dict, verbose_name='material settings')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='customization_thumbnails/', verbose_name='configuration thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('car_3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='main.car3dmodel')),
                ('selected_parts_3d', models.ManyToManyField(blank=True, to='main.part3dmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_customizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user car customization',
                'verbose_name_plural': 'user car customizations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GLBFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='file name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file_type', models.CharField(choices=[('CAR', 'Car Model'), ('PART', 'Part Model'), ('TEXTURE', 'Texture'), ('ENV', 'Environment'), ('OTHER', 'Other')], default='OTHER', max_length=10, verbose_name='file type')),
                ('glb_file', models.FileField(help_text='Upload GLB 3D model file', upload_to='3d_models/glb/', verbose_name='GLB file')),
                ('thumbnail', models.ImageField(blank=True, help_text='Preview image of the 3D model', null=True, upload_to='3d_models/thumbnails/', verbose_name='thumbnail')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='file size (bytes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('car_model', models.ForeignKey(blank=True, help_text='Associated car model (if file type is CAR)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glb_files', to='main.car3dmodel')),
                ('part_model', models.ForeignKey(blank=True, help_text='Associated part model (if file type is PART)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glb_files', to='main.part3dmodel')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_glb_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GLB file',
                'verbose_name_plural': 'GLB files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomizationLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.usercarcustomization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customization like',
                'verbose_name_plural': 'customization likes',
                'unique_together': {('user', 'customization')},
            },
        ),
    ]
