# Generated by Django 4.2.7 on 2025-07-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_car3dmodel_part3dcategory_part3dmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='car model name')),
                ('brand', models.CharField(max_length=100, verbose_name='car brand')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('model_file', models.FileField(upload_to='3d_models/cars/', verbose_name='3D model file (OBJ/GLB)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='3d_models/thumbnails/', verbose_name='thumbnail image')),
                ('default_colors', models.JSONField(blank=True, default=dict, help_text='JSON object with color names and hex codes', verbose_name='default colors')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': '3D Car Model',
                'verbose_name_plural': '3D Car Models',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='customizationlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customizationlike',
            name='customization',
        ),
        migrations.RemoveField(
            model_name='customizationlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='glbfile',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='glbfile',
            name='part_model',
        ),
        migrations.RemoveField(
            model_name='glbfile',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='part3dmodel',
            name='category_3d',
        ),
        migrations.RemoveField(
            model_name='part3dmodel',
            name='compatible_cars_3d',
        ),
        migrations.RemoveField(
            model_name='part3dmodel',
            name='spare_part',
        ),
        migrations.RemoveField(
            model_name='usercarcustomization',
            name='car_3d',
        ),
        migrations.RemoveField(
            model_name='usercarcustomization',
            name='selected_parts_3d',
        ),
        migrations.RemoveField(
            model_name='usercarcustomization',
            name='user',
        ),
        migrations.DeleteModel(
            name='Car3DModel',
        ),
        migrations.DeleteModel(
            name='CustomizationLike',
        ),
        migrations.DeleteModel(
            name='GLBFile',
        ),
        migrations.DeleteModel(
            name='Part3DCategory',
        ),
        migrations.DeleteModel(
            name='Part3DModel',
        ),
        migrations.DeleteModel(
            name='UserCarCustomization',
        ),
    ]
