# Generated by Django 6.1.1 on 2026-09-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarModel3D",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="car model name"),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="car brand")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "model_file",
                    models.FileField(
                        upload_to="3d_models/cars/",
                        verbose_name="3D model file (OBJ/GLB)",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="3d_models/thumbnails/",
                        verbose_name="thumbnail image",
                    ),
                ),
                (
                    "default_colors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object with color names and hex codes",
                        verbose_name="default colors",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "3D Car Model",
                "verbose_name_plural": "3D Car Models",
                "ordering": ["brand", "name"],
                "indexes": [
                    models.Index(
                        fields=["brand", "name"], name="car_model_3d_brand_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VehicleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="category name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "vehicle category",
                "verbose_name_plural": "vehicle categories",
                "indexes": [
                    models.Index(fields=["name"], name="unique_vehicle_category")
                ],
            },
        ),
        migrations.CreateModel(
            name="VehicleBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="brand name"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="vehicle.vehiclecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle brand",
                "verbose_name_plural": "vehicle brands",
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="model name")),
                ("year_from", models.PositiveIntegerField(verbose_name="year from")),
                (
                    "year_to",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="year to"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="vehicle.vehiclebrand",
                    ),
                ),
            ],
            options={
                "verbose_name": "vehicle model",
                "verbose_name_plural": "vehicle models",
            },
        ),
        migrations.AddIndex(
            model_name="vehiclebrand",
            index=models.Index(
                fields=["name", "category"], name="unique_brand_per_category"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclemodel",
            index=models.Index(fields=["name", "brand"], name="unique_model_per_brand"),
        ),
        migrations.AlterUniqueTogether(
            name="vehiclemodel",
            unique_together={("name", "brand")},
        ),
    ]
