# Generated by Django 6.1.1 on 2026-09-14 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0003_alter_part3dmodels_options_and_more"),
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel3d",
            name="modified_part",
            field=models.ForeignKey(
                blank=True,
                help_text="The modified part associated with this 3D car model",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_models_3d",
                to="parts.part3dmodels",
            ),
        ),
    ]
