# Generated by Django 6.1.1 on 2026-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel3d',
            name='alloy_wheels',
            field=models.JSONField(blank=True, default=list, help_text='List of wheel objects with name, price, description', verbose_name='alloy wheels options'),
        ),
        migrations.AddField(
            model_name='carmodel3d',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='base price'),
        ),
        migrations.AddField(
            model_name='carmodel3d',
            name='spoilers',
            field=models.JSONField(blank=True, default=list, help_text='List of spoiler objects with name, price, description', verbose_name='spoiler options'),
        ),
    ]
