# Generated by Django 6.1.1 on 2026-09-14 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0002_carmodel3d_modified_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel3d",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent 3D car model, if this is a variant or child model",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="vehicle.carmodel3d",
            ),
        ),
    ]
