# Generated by Django 6.1.1 on 2026-09-10 17:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicle", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MechanicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="license number"
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="years of experience"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="professional description"
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True, verbose_name="certifications and qualifications"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="province"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="district"
                    ),
                ),
                (
                    "service_area",
                    models.TextField(
                        blank=True, verbose_name="service area description"
                    ),
                ),
                (
                    "is_mobile",
                    models.BooleanField(default=False, verbose_name="mobile mechanic"),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="hourly rate",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="business name"
                    ),
                ),
                (
                    "business_address",
                    models.TextField(blank=True, verbose_name="business address"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="available for hire"
                    ),
                ),
                (
                    "service_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="service rating",
                    ),
                ),
                (
                    "total_service_ratings",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total service ratings"
                    ),
                ),
                (
                    "total_jobs_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total jobs completed"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="specialist_mechanics",
                        to="vehicle.vehiclecategory",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "MECHANIC"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanic_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "mechanic profile",
                "verbose_name_plural": "mechanic profiles",
            },
        ),
        migrations.CreateModel(
            name="MechanicAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=10,
                        verbose_name="day of week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="available"),
                ),
                (
                    "mechanic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="mechanic.mechanicprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "mechanic availability",
                "verbose_name_plural": "mechanic availability",
            },
        ),
        migrations.CreateModel(
            name="MechanicService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("ENGINE_REPAIR", "Engine Repair"),
                            ("BRAKE_SERVICE", "Brake Service"),
                            ("TRANSMISSION", "Transmission Repair"),
                            ("ELECTRICAL", "Electrical Systems"),
                            ("AC_SERVICE", "AC Service"),
                            ("BODY_WORK", "Body Work & Painting"),
                            ("TIRE_SERVICE", "Tire Service"),
                            ("OIL_CHANGE", "Oil Change"),
                            ("INSPECTION", "Vehicle Inspection"),
                            ("TOWING", "Towing Service"),
                            ("EMERGENCY", "Emergency Repair"),
                            ("OTHER", "Other Service"),
                        ],
                        max_length=20,
                        verbose_name="service type",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="service name")),
                ("description", models.TextField(verbose_name="service description")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="base price"
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="price per hour",
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="estimated duration (minutes)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "compatible_vehicles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="available_services",
                        to="vehicle.vehiclecategory",
                    ),
                ),
                (
                    "mechanic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="mechanic.mechanicprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "mechanic service",
                "verbose_name_plural": "mechanic services",
            },
        ),
        migrations.CreateModel(
            name="MechanicHireRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("ON_SITE", "On-Site (Customer Location)"),
                            ("SHOP", "At Mechanic Shop"),
                            ("ROADSIDE", "Roadside Assistance"),
                        ],
                        default="SHOP",
                        max_length=15,
                        verbose_name="job type",
                    ),
                ),
                (
                    "problem_description",
                    models.TextField(verbose_name="problem description"),
                ),
                ("vehicle_info", models.TextField(verbose_name="vehicle information")),
                (
                    "service_location",
                    models.TextField(blank=True, verbose_name="service location"),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="preferred date"
                    ),
                ),
                (
                    "preferred_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="preferred time"
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="scheduled date"
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="scheduled time"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="estimated cost",
                    ),
                ),
                (
                    "final_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="final cost",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                (
                    "mechanic_notes",
                    models.TextField(blank=True, verbose_name="mechanic notes"),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="customer notes"),
                ),
                (
                    "work_completed",
                    models.TextField(blank=True, verbose_name="work completed"),
                ),
                ("parts_used", models.TextField(blank=True, verbose_name="parts used")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hire_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mechanic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hire_requests",
                        to="mechanic.mechanicprofile",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hire_requests",
                        to="mechanic.mechanicservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "mechanic hire request",
                "verbose_name_plural": "mechanic hire requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mechanicprofile",
            index=models.Index(fields=["user"], name="unique_mechanic_profile"),
        ),
        migrations.AddIndex(
            model_name="mechanicavailability",
            index=models.Index(
                fields=["mechanic", "day_of_week"], name="mechanic_availability_index"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mechanicavailability",
            unique_together={("mechanic", "day_of_week")},
        ),
        migrations.AddIndex(
            model_name="mechanicservice",
            index=models.Index(
                fields=["mechanic", "service_type"], name="mechanic_service_index"
            ),
        ),
        migrations.AddIndex(
            model_name="mechanichirerequest",
            index=models.Index(
                fields=["customer", "mechanic"], name="customer_mechanic_index"
            ),
        ),
        migrations.AddIndex(
            model_name="mechanichirerequest",
            index=models.Index(fields=["status"], name="hire_request_status_index"),
        ),
    ]
