# Generated by Django 6.1.1 on 2026-09-10 17:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0001_initial"),
        ("vehicle", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SparePartCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="category name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="parts.sparepartcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "spare part category",
                "verbose_name_plural": "spare part categories",
            },
        ),
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="part name")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "part_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="part number"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="province"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="district"
                    ),
                ),
                (
                    "location_address",
                    models.TextField(blank=True, verbose_name="location address"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("USED", "Used"),
                            ("REFURBISHED", "Refurbished"),
                        ],
                        default="NEW",
                        max_length=15,
                        verbose_name="condition",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="quantity"),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="spare_parts/",
                        verbose_name="main image",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="average rating",
                    ),
                ),
                (
                    "total_ratings",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total ratings"
                    ),
                ),
                (
                    "total_sales",
                    models.PositiveIntegerField(default=0, verbose_name="total sales"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "compatible_vehicles",
                    models.ManyToManyField(
                        related_name="compatible_parts", to="vehicle.vehiclemodel"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spare_parts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="shop.shop",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="parts.sparepartcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "spare part",
                "verbose_name_plural": "spare parts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SparePartImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="spare_parts/", verbose_name="image"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="caption"
                    ),
                ),
                (
                    "spare_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="parts.sparepart",
                    ),
                ),
            ],
            options={
                "verbose_name": "spare part image",
                "verbose_name_plural": "spare part images",
            },
        ),
        migrations.AddIndex(
            model_name="sparepartcategory",
            index=models.Index(fields=["name"], name="unique_spare_part_category"),
        ),
        migrations.AddIndex(
            model_name="sparepart",
            index=models.Index(
                fields=["name", "category"], name="spare_part_name_category"
            ),
        ),
        migrations.AddIndex(
            model_name="sparepartimage",
            index=models.Index(fields=["spare_part"], name="spare_part_image_index"),
        ),
    ]
