# Generated by Django 6.1.1 on 2026-09-13 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part3dmodels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="3D model name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "model_file",
                    models.FileField(
                        upload_to="3d_models/parts/",
                        verbose_name="3D model file (OBJ/GLB)",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="3d_models/thumbnails/",
                        verbose_name="thumbnail image",
                    ),
                ),
                (
                    "default_colors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object with color names and hex codes",
                        verbose_name="default colors",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_models",
                        to="parts.sparepart",
                    ),
                ),
            ],
            options={
                "verbose_name": "3D Part Model",
                "verbose_name_plural": "3D Part Models",
                "ordering": ["part", "name"],
                "indexes": [
                    models.Index(
                        fields=["part", "name"], name="part_3d_model_part_name"
                    )
                ],
            },
        ),
    ]
