# Generated by Django 6.1.1 on 2026-09-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0002_part3dmodels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="part3dmodels",
            options={
                "verbose_name": "3D Part Model",
                "verbose_name_plural": "3D Part Models",
            },
        ),
        migrations.RemoveIndex(
            model_name="part3dmodels",
            name="part_3d_model_part_name",
        ),
        migrations.RemoveField(
            model_name="part3dmodels",
            name="part",
        ),
    ]
